/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as ApiRoomsCodeDocRouteImport } from './routes/api/rooms.$code.doc'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomsCodeDocRoute = ApiRoomsCodeDocRouteImport.update({
  id: '/api/rooms/$code/doc',
  path: '/api/rooms/$code/doc',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/r/$code': typeof RCodeRoute
  '/api/rooms/$code/doc': typeof ApiRoomsCodeDocRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/r/$code': typeof RCodeRoute
  '/api/rooms/$code/doc': typeof ApiRoomsCodeDocRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/r/$code': typeof RCodeRoute
  '/api/rooms/$code/doc': typeof ApiRoomsCodeDocRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/r/$code' | '/api/rooms/$code/doc'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/r/$code' | '/api/rooms/$code/doc'
  id: '__root__' | '/' | '/r/$code' | '/api/rooms/$code/doc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RCodeRoute: typeof RCodeRoute
  ApiRoomsCodeDocRoute: typeof ApiRoomsCodeDocRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms/$code/doc': {
      id: '/api/rooms/$code/doc'
      path: '/api/rooms/$code/doc'
      fullPath: '/api/rooms/$code/doc'
      preLoaderRoute: typeof ApiRoomsCodeDocRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RCodeRoute: RCodeRoute,
  ApiRoomsCodeDocRoute: ApiRoomsCodeDocRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
